### ISSUE TITLE
Would it be possible to migrate to OrientDB 2.2.16?

### ISSUE THREAD

**Issue by karolmie1** [xvik/dropwizard-orient-server#4]
Should be one liner.

**Comment by xvik** [comment]
Can you override transitive dependency by directly declaring newer orient version in your build?
Please tell me if there are problems (incompatibilities) with it and I'll make bugfix release.

I could release with updated dependency but I don't want to do it for each minor version (they release it too often).

**Comment by karolmie1** [comment]
Tests fail - cannot open studio. Manual navigation to the site confirms that. They changed studio from 'org.t:2.2.0' to  'com.orientechnologies:orientdb-studio:2.2.16', so maybe this is be a problem? Or do I have to create webjar first in this repository?: https://github.com/webjars/orientdb-studio

`java.io.FileNotFoundException: http://localhost:2480/studio/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at ru.vyarus.dropwizard.orient.StartApplicationTest.Check server starts correctly(StartApplicationTest.groovy:30)`


Version 2.2.10 is pretty solid though and it won't be the end of the world if i cannot use the newest stuff. Awesome wrapper by the way!

**Comment by xvik** [comment]
Mmmm I forgot! They finally released studio as separate jar!
Thank you for reminding :) 

I will add support.

**Comment by xvik** [comment]
It appears that studio jar does not actually contain studio. 
Studio build was just fixed, so I will have to wait for orient 2.2.17 release to finish integration.

**Comment by karolmie1** [comment]
2.2.17 is released. Hopefully studio jar will contain studio this time xD

**Comment by xvik** [comment]
Studio jar support is already committed, but I want to also improve configuration support before release. Should be ready soon.

**Comment by xvik** [comment]
[Released](https://github.com/xvik/dropwizard-orient-server/releases/tag/2.0.0)
