### ISSUE TITLE
Minor Orientdb release, and major dropwizard release -> upgrade possible?

### ISSUE THREAD

**Issue by karolmie1** [xvik/dropwizard-orient-server#6]
Hello!
Recently Orientdb released version 2.2.18 (fixing particularly nasty bug for me).
In this case update is trivial (tests run ok, and orientdb just works with this version (tested on my project on local artifact)).

Dropwizard also made release recently - 1.1.0 (changelog: https://github.com/dropwizard/dropwizard/releases )

Here it starts to be harder, as simple version upgrade does not pass tests.

Would it be possible to somehow fix this and upgrade those artifacts versions?

**Comment by xvik** [comment]
Hi! I will look.

**Comment by xvik** [comment]
Dropwizard 1.1.0 calls System.exit on any error (instead of throwing error, as before). That was the reason for some tests to fail (they were fixed in trunk).
Overall, nothing is broken, so I see no reason to release the new version with just updated dependencies.

**Comment by karolmie1** [comment]
That's fair. Shame its so hard to come up with versioning system that immediately allows to distinguish orientdb and dropwizard version.

I think that I had some problems with my app thought, but it seems to be my fault then. I'll just check it out again, and then close the issue.

**Comment by karolmie1** [comment]
Yup, f-up entirely on my part!
