### ISSUE TITLE
Admin servlet link not valid when configured orientdb for https

### ISSUE THREAD

**Issue by karolmie1** [xvik/dropwizard-orient-server#7]
There is no auto-redirect, or direct link to https:// site when dropwizard is configured to run with https.
That of course causes ERR_INVALID_HTTP_RESPONSE.

It would be nice if this link changed automatically, depending on the configuration.

**Comment by xvik** [comment]
Could you please show me configuration example so I could better understand what you mean?

**Comment by karolmie1** [comment]
Ok, I've looked a lil bit closer.
If you use https for admin, then link will point to proper https orientdb address. The strange thing is that this address still is somehow "autoredirected" to http version. So, link shows https, but browser (FF, Chrome) on both Windows and Linux opens http version, and I still have to change address manually. 

Even stranger: when I "copy link address", and paste it it goes to wrong url, but when I change url manually, and copy it again, then pasting it causes it to go to correct url.

But this is probably browser fault, and probably can't be fixed from here. In fact I'm gonna ask stackoverflow of this peculiar behavior.

Second scenario:
when orientdb is using https, while dropwizard is using http, link explicitly shows http version, but that's really uncommon configuration and I understand that it is not worth supporting.

Feel free to close.

**Comment by xvik** [comment]
I will try to reproduce. 

It's more likely that orient (it's http server part) do redirects itself. Probably this is due to musconfiguration.. need to look closer.
Please add stackoverflow link here too for reference.

**Comment by karolmie1** [comment]
Stackoverflow reference: https://stackoverflow.com/questions/45483767/unexpected-url-change-when-following-href

**Comment by xvik** [comment]
New version [released](https://github.com/xvik/dropwizard-orient-server/releases/tag/2.1.0) with [a lot of ssl related improvements](https://github.com/xvik/dropwizard-orient-server/wiki/SSL)
